spring.application.name: api_invocations

spring:
  data:
    mongodb:
      uuid-representation: standard
      database: api_invocationsdb
      port: 27017

# Configuration des APIs externes
external:
  api:
    monsters-base-url: http://api_monsters:8080
    player-base-url: http://api_joueur:8080
    connection-timeout: 5000
    read-timeout: 5000
