services:
  mongo:
    image: mongo
    container_name: api_invocations_mongo
    ports:
      - "27017:27017"

  api_invocations:
    build: ../
    container_name: api_invocations
    ports:
      - "8085:8080"
